### 📦 Get Cart
GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMmY4ZWQ3ZC1iMGQ4LTQzNDItODIzNC1lMTE4YWI4NmI3MDAiLCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzUzMTA2MDc3LCJleHAiOjE3NTMxNDkyNzd9.Inzozfj-YaIhHg0Q8DkPiSk9E8m0-6sRVUi4h52uVIo


### ➕ Add to Cart
POST http://localhost:3000/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMmY4ZWQ3ZC1iMGQ4LTQzNDItODIzNC1lMTE4YWI4NmI3MDAiLCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzUzMTA2MDc3LCJleHAiOjE3NTMxNDkyNzd9.Inzozfj-YaIhHg0Q8DkPiSk9E8m0-6sRVUi4h52uVIo

{
  "productId": "dd470007-41c8-4a32-b11a-cb98d4d0587b",
  "quantity": 9
}


### ✏️ Update Cart Item Quantity
PATCH http://localhost:3000/cart/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMmY4ZWQ3ZC1iMGQ4LTQzNDItODIzNC1lMTE4YWI4NmI3MDAiLCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzUzMTA2MDc3LCJleHAiOjE3NTMxNDkyNzd9.Inzozfj-YaIhHg0Q8DkPiSk9E8m0-6sRVUi4h52uVIo

{
  "productId": "97991d6b-2df3-4e37-9a3c-7caff01412b4",
  "quantity": 5
}

### ❌ Remove Item from Cart
DELETE http://localhost:3000/cart/remove?productId=dd470007-41c8-4a32-b11a-cb98d4d0587b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMmY4ZWQ3ZC1iMGQ4LTQzNDItODIzNC1lMTE4YWI4NmI3MDAiLCJlbWFpbCI6InRlc3R1c2VyMUBleGFtcGxlLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzUzMTA2MDc3LCJleHAiOjE3NTMxNDkyNzd9.Inzozfj-YaIhHg0Q8DkPiSk9E8m0-6sRVUi4h52uVIo
